--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/cooldogepm/BedrockEconomy
build-by-default: true
branches:
- main
- pm5
projects:
  BedrockEconomy:
    path: ""
    libs:
      - src: cooldogepm/libSQL/libSQL
        version: ^0.2.5
        branch: pm5
      - src: ACM-PocketMine-MP/Commando/Commando
        version: ^3.2.1
      - src: SOF3/await-generator/await-generator
        version: ^3.6.1
    lint:
      phpstan: false
      syntaxError: false
...

